Use TJWHTOOLS_INSTALL_ROOT consistently
Signed-off-by: Toby Haynes <thaynes@ca.ibm.com>

diff --git a/perf/db2mon_tools/etc/profile b/perf/db2mon_tools/etc/profile
--- a/perf/db2mon_tools/etc/profile
+++ b/perf/db2mon_tools/etc/profile
@@ -5,7 +5,7 @@
 # Environment variables that need to be set
 # TJWHTOOLS_INSTALL_ROOT should be an absolute path to the db2mon_tools
 export TJWHTOOLS_INSTALL_ROOT=$HOME/db2-samples/perf/db2mon_tools
-   
+
 # Perl needs more than the default data segment size on many systems.
 # Use at least this size and more if possible.
 
@@ -27,12 +27,12 @@ export TJWHTOOLS_INSTALL_ROOT=$HOME/db2-samples/perf/db2mon_tools
 
 # ========================================================================
 # Do not alter code below this line
-# 
-if [ -d "$TJWHTOOLS_INSTALL_ROOT" ]; then
-    export PATH="${PATH}:${TJWHTOOLS_INSTALL_PATH}/bin"
-    export PERL5LIB="${PERL5LIB}:${TJWHTOOLS_INSTALL_PATH}/perllib"
+#
+if [ -d "${TJWHTOOLS_INSTALL_ROOT}" ]; then
+    export PATH="${PATH}:${TJWHTOOLS_INSTALL_ROOT}/bin"
+    export PERL5LIB="${PERL5LIB}:${TJWHTOOLS_INSTALL_ROOT}/perllib"
 else
     # Warn (on STDERR) if this is not set
-    echo "ERROR: TJWHTOOLS_INSTALL_PATH is set to $TJWHTOOLS_INSTALL_ROOT but is not a directory" 2>&
+    >&2 echo "ERROR: TJWHTOOLS_INSTALL_ROOT is set to ${TJWHTOOLS_INSTALL_ROOT} but is not a directory"
 fi
 
